---
- name:  Playbook for remote command/script execution
  hosts: all 
  become: yes
  remote_user: ubuntu
  tasks:
  - name: stop the docker-compose down
    shell: sudo docker-compose down
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
  - name: Remove the unused container and docker images
    shell: sudo docker system prune -a -f
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
  - name: change the directory and unzip the f.zip file
    shell: 'cd /home/ubuntu/be/'
    shell: pwd
    register: myoutput1
  - debug: msg={{ myoutput1.stdout}}
  - name: unzip the f.zip file
    shell: unzip -o /home/ubuntu/be/f.zip
    shell: ls -latr
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
  - name: Start the docker-compose up
    shell: sudo docker-compose up -d
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
