---
- name:  Playbook for dockerfile/script execution
  hosts: all 
  become: yes
  remote_user: ec2-user
  vars:
    docker_cmd:  "{{ docker_cmd }}"
    image_tag:  "{{ image_tag }}"
    container_name:  "{{ container_name }}"
    
  tasks:
  - name: Get ECR login password
 #   command: aws ecr get-login-password --region us-east-2
    command: aws ecr get-login-password --region us-east-2
    register: ecr_login_password
    
  - debug: var=ecr_login_password
  
  - name: Login to ECR 255581990649.dkr.ecr.us-east-2.amazonaws.com
 #   command: aws ecr get-login-password --region us-east-2
    command: sudo docker login -u AWS -p {{ ecr_login_password.stdout }} 255581990649.dkr.ecr.us-east-2.amazonaws.com
    register: myoutput1
  - name: Stop and remove the running container and images 
    command: sudo docker stop api
    register: myoutput2
    command: sudo docker container rm -f api
    register: myoutput23
    command: sudo docker image prune -af
    register: myoutput24
  - name: Pull the image from ECR Image TAG should pass from Ansiable
 #   command:  sudo docker pull 255581990649.dkr.ecr.us-east-2.amazonaws.com/dev-ecr-repository:latest 
    #command:  sudo docker pull 255581990649.dkr.ecr.us-east-2.amazonaws.com/dev-ecr-repository:{{ image_tag }}
    command:  sudo docker stop -t 60 {{ container_name }}
    register: myoutput2
  - debug: msg={{ myoutput2.stdout }}  
  - name: Run the container
    shell: sudo {{ docker_cmd }}
    register: myoutput3
  - debug: msg={{ myoutput3.stdout }}
  - name: Check the service
    shell: sudo docker ps -a
    register: myoutput4
  - debug: msg={{ myoutput4.stdout }}
