---
- name:  Playbook for dockerfile/script execution
  hosts: all 
  become: yes
  remote_user: ec2-user
  vars:
    docker_cmd:  "{{ docker_cmd }}"
  tasks:
  - name: Login to ECR 255581990649.dkr.ecr.us-east-2.amazonaws.com
    command: aws ecr get-login-password --region us-east-2
    register: myoutput
  - name: Pull the image from ECR Image TAG should pass from Ansiable
    command:  sudo docker pull 255581990649.dkr.ecr.us-east-2.amazonaws.com/dev-ecr-repository:latest 
    register: myoutput
  - debug: msg={{ myoutput.stdout}}  
  - name: Run the container
    shell: sudo {{ docker_cmd }}
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
  - name: Check the service
    shell: sudo docker ps -a
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
