---
- name:  Playbook for remote command/script execution
  hosts: all 
  become: yes
  #remote_user: ec2-user
  tasks:
  - name: Return motd to registered var
    command: cat /etc/motd
    register: mymotd
  - name: list out the files
    command: ls -ltr 
    register: myoutput
  - name: Executing a Command Using Shell Module 
    shell: ls -lrt > temp.txt
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
  - name: Executing a command using command module
    command: cat temp.txt
    register: myoutput
  - debug: msg={{ myoutput.stdout}}
  - name: Ansible command module multiple commands 
    command: "touch {{ item }}"
    with_items: 
        - hello.txt 
        - hello2.txt 
        - hello3.txt 
    args:
      chdir: /var/
