--- 
- 
  become: true
  hosts: all
  name: "Playbook for remote command/script execution"
  vars_prompt: 
    - 
      name: username
      private: false
      prompt: "What is your username?"
    - 
      name: rrr
      password: rr
  tasks: 
    - 
      name: "executing commadn"
