---
- name:  This is a sample shellscript playbook to create a file 
  hosts: ip-172-16-0-178.us-east-2.compute.internal
  become: true
  
  tasks:
  - name: Create a files
    shell: touch /home/ec2-user/file1.txt
