---
- name:  This is a sample shellscript playbook to create a file 
  hosts: asg
  become: true
  remote_user: ec2-user
  
  tasks:
  - name: Create shellscript and execute
    shell: touch /home/ec2-user/file2.txt
    shell: cd /home/ec2-user
    shell: ls -ltr
